### PR TITLE
Unauthorized invoice endpoint

### PR DESCRIPTION
**Pull request by skosito**
Used the same logic as addInvoice, just getting user from db first instead of getting it from token.

### CODE REVIEW

**Comment by bumi** [comment]
@godSaysHODL can you have a look? is this how you imagine it?

**Comment by godSaysHODL** [comment]
Yes, it looks great from my very untrained eyes 👁️👁️🙌

**Review by bumi — COMMENTED** [review]
we should add a spec

**Comment by kiwiidb** [comment]
What do you mean by "spec" ?

**Comment by bumi** [comment]
sorry, I mean "tests".

(in ruby we often use specs)

**Comment by skosito** [comment]
> sorry, I mean "tests".
> 
> (in ruby we often use specs)

sure, good point, i will add tests, and then we can continue review

**Comment by kiwiidb** [comment]
Looks good, some basic tests and then this can be merged

**Comment by skosito** [comment]
@bumi @kiwiidb I added simple tests, please check again.

**Review by kiwiidb — APPROVED** [review]

**Pull request merged**
